version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - env_secrets
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

secrets:
  env_secrets:
    file: ./.env.secrets